window.identifier = "2023";
let fileformat = "";

const AUDIOPLAYER_TITLE = document.getElementById("AUDIOPLAYER_TITLE");
const AUDIOPLAYER_SUB = document.getElementById("AUDIOPLAYER_SUB");

let musicPlayer = document.getElementById("music_player");
let BLOB_LINK_SRC = null;
let lastUrl = null;
const AUDIOPLAYER_ICON = document.getElementById("AUDIOPLAYER_ICON");
const AUDIOPLAYER_PLAYBTN = document.getElementById("AUDIOPLAYER_PLAYBTN");
const AUDIOPLAYER_SLIDER = document.getElementById("AUDIOPLAYER_SLIDER");
const AUDIOPLAYER_DOWNLOAD = document.getElementById("AUDIOPLAYER_DOWNLOAD");

function API_MUSICSEARCH(query) {
  if (query === undefined) {
    query = document.getElementById("MUSICSEARCH_BOX")?.value ?? "";
  }

  const table = document.getElementById("tablex");
  const body = table?.tBodies[0];
  if (!body) return;

  const search = String(query ?? "").trim().toLocaleLowerCase();
  Array.from(body.rows).forEach((row) => {
    const title = row.cells[0]?.textContent ?? "";
    row.style.display = title.toLocaleLowerCase().includes(search)
      ? "table-row"
      : "none";
  });
}

async function API_MUSIC_GET(id) {
    const table = document.getElementById("tablex");
    const audio = musicPlayer;

    if (!table || !audio) return;

    table.innerHTML = "";

    const identifier = id;

    try {
        /*
         * Get generated music metadata JSON
         *
         * Example:
         * id = "2022"
         *
         * → ./api/music/music-2022.json
         */
        const response = await fetch(
            `./api/music/music-${identifier}.json`
        );

        if (!response.ok) {
            throw new Error(
                `Music metadata failed: HTTP ${response.status}`
            );
        }

        const data = await response.json();

        if (!Array.isArray(data)) {
            console.error("Invalid music metadata JSON.");
            return;
        }

        const parent = table.tBodies[0] || table.createTBody();

        /*
         * Get each music entry
         */
        data.forEach((file) => {
            if (!file || typeof file !== "object") return;

            const title = file.title || "Unknown Title";
            const artist = file.artist || "";
            const album = file.album || "";
            const fileName = file.file || "";

            /*
             * Artwork generated by Node.js
             */
            const picture = "./api/music/" + file.picture || "";

            /*
             * Music file URL
             *
             * If the JSON is in:
             * ./api/music/music-2022.json
             *
             * and music is:
             * ./api/music/music-2022/Song.mp3
             *
             * then this resolves correctly.
             */
            const url = fileName
                ? `./api/music/music-${identifier}/${fileName
                    .split("/")
                    .map(encodeURIComponent)
                    .join("/")}`
                : "";

            const format = fileName
                ? fileName.split(".").pop().toUpperCase()
                : "";

            /*
             * Create table row
             */
            const row = document.createElement("tr");

            row.className = "music_main";
            row.tabIndex = 0;
            row.style.display = "table-row";

            const cell = document.createElement("td");

            cell.colSpan = 3;
            cell.style.display = "table-cell";

            /*
             * Create music information line
             */
            const createLine = (icon, value, subtitle) => {
                const line = document.createElement("div");

                const main = document.createElement("span");

                main.innerHTML = `${icon} ${value}`;

                const small = document.createElement("small");

                small.textContent = subtitle;
                small.style.display = "block";

                line.append(main, small);

                return line;
            };

            cell.append(
                createLine(
                    `<img src="./assets/icons/music.svg" width="12px" class="tint"/>`,
                    title,
                    artist
                ),

                createLine(
                    "",
                    album,
                    format
                )
            );

            row.appendChild(cell);

            /*
             * Click → play
             */
            const play = async () => {
                if (!url || url === lastUrl) {
                    return;
                }

                lastUrl = url;

                AUDIOPLAYER_TITLE.textContent = title;
                AUDIOPLAYER_SUB.textContent = artist;

                /*
                 * Media Session
                 */
                if (
                    "mediaSession" in navigator &&
                    navigator.mediaSession
                ) {
                    navigator.mediaSession.metadata =
                        new MediaMetadata({
                            title,
                            artist,
                            album,
                            artwork: picture
                                ? [
                                    {
                                        src: picture,
                                        type: "image/webp"
                                    }
                                ]
                                : []
                        });
                }

                /*
                 * Release previous Blob URL
                 */
                if (BLOB_LINK_SRC) {
                    URL.revokeObjectURL(BLOB_LINK_SRC);
                    BLOB_LINK_SRC = null;
                }

                fileformat = fileName;

                try {
                    /*
                     * Fetch MP3
                     */
                    const response = await fetch(url);

                    if (!response.ok) {
                        throw new Error(
                            `Track load failed: HTTP ${response.status}`
                        );
                    }

                    /*
                     * Convert to Blob
                     */
                    BLOB_LINK_SRC = await response.blob();

                    /*
                     * Create temporary Blob URL
                     */
                    audio.src = BLOB_LINK_SRC
                        ? URL.createObjectURL(BLOB_LINK_SRC)
                        : url;

                } catch (error) {
                    BLOB_LINK_SRC = null;

                    console.error(
                        "Unable to prepare the track:",
                        error
                    );

                    return;
                }

                audio.load();

                audio.play().catch(console.error);
            };

            /*
             * Mouse
             */
            row.addEventListener("click", play);

            /*
             * Keyboard
             */
            row.addEventListener("keydown", (event) => {
                if (
                    event.key === "Enter" ||
                    event.key === " "
                ) {
                    event.preventDefault();
                    play();
                }
            });

            parent.appendChild(row);
        });

    } catch (error) {
        console.error(
            "Unable to load music metadata:",
            error
        );
    }
}

if (AUDIOPLAYER_DOWNLOAD && musicPlayer) {
  AUDIOPLAYER_DOWNLOAD.addEventListener("click", async () => {
    if (!BLOB_LINK_SRC) return;

    try {
      const objectUrl = URL.createObjectURL(BLOB_LINK_SRC);
      const link = document.createElement("a");
      link.href = objectUrl;
      link.download = fileformat;
      link.click();
    } catch (error) {
      console.error("Unable to download the current track:", error);
    }
  });
}

let UPDATE_ON_NONINPUT = true;

if (musicPlayer) {
  AUDIOPLAYER_SLIDER.addEventListener("mouseenter", () => {
    UPDATE_ON_NONINPUT = false;
  });
  AUDIOPLAYER_SLIDER.addEventListener("mouseleave", () => {
    UPDATE_ON_NONINPUT = true;
  });
  AUDIOPLAYER_SLIDER.addEventListener("touchstart", () => {
    UPDATE_ON_NONINPUT = false;
  });
  AUDIOPLAYER_SLIDER.addEventListener("touchend", () => {
    UPDATE_ON_NONINPUT = true;
  });
  AUDIOPLAYER_SLIDER.addEventListener("touchcancel", () => {
    UPDATE_ON_NONINPUT = true;
  });

  const setPlayerState = (state) => {
    const icon = state ? "pause" : "play_arrow";
    AUDIOPLAYER_ICON.src = "../assets/icons/" + icon + ".svg";
  };

  const updatePlayerProgress = () => {
    if (!UPDATE_ON_NONINPUT) return;

    const progress = musicPlayer.duration
      ? (musicPlayer.currentTime / musicPlayer.duration) * 100
      : 0;

    AUDIOPLAYER_SLIDER.style.backgroundSize = progress + "% 100%";
    const clamped = Math.min(100, Math.max(0, progress));
    musicPlayer.dataset.progress = String(clamped);
    musicPlayer.setAttribute("data-progress", String(clamped));
    AUDIOPLAYER_SLIDER.value = progress;
  };

  const seek = (e) => {
    if (!Number.isFinite(musicPlayer.duration) || musicPlayer.duration <= 0)
      return;

    const value = Number(e.target.value);
    if (!Number.isFinite(value)) return;

    const progress = Math.min(100, Math.max(0, value));
    e.target.style.backgroundSize = progress + "% 100%";
    musicPlayer.currentTime = (progress / 100) * musicPlayer.duration;
  };

  const seek_notaudio = (e) => {
    if (!Number.isFinite(musicPlayer.duration) || musicPlayer.duration <= 0)
      return;

    const value = Number(e.target.value);
    if (!Number.isFinite(value)) return;

    const progress = Math.min(100, Math.max(0, value));
    e.target.style.backgroundSize = progress + "% 100%";
  };

  AUDIOPLAYER_SLIDER.addEventListener("change", seek);
  AUDIOPLAYER_SLIDER.addEventListener("input", seek_notaudio);

  AUDIOPLAYER_PLAYBTN.addEventListener("click", () => {
    if (musicPlayer.paused) {
      musicPlayer.play();
    } else {
      musicPlayer.pause();
    }
  });

  musicPlayer.addEventListener("play", () => setPlayerState(true));
  musicPlayer.addEventListener("pause", () => setPlayerState(false));
  musicPlayer.addEventListener("ended", () => setPlayerState(false));
  musicPlayer.addEventListener("timeupdate", updatePlayerProgress);
  musicPlayer.addEventListener("loadedmetadata", updatePlayerProgress);

  setPlayerState(!musicPlayer.paused);
  updatePlayerProgress();
}

const API_MUSICFETCH = (e) => {
  window.identifier = document.getElementById("API_MUSIC_CATEGORY")?.value;
  API_MUSIC_GET(window.identifier);
};

API_MUSIC_GET(window.identifier);

function API_PLAYER_SCROLL() {
  const player = document.querySelector(".player");

  if (!player) return;

  const atBottom =
    window.innerHeight + window.scrollY >=
    document.documentElement.scrollHeight - 2;

  player.classList.toggle("at-bottom", atBottom);
}

window.addEventListener("scroll", API_PLAYER_SCROLL, { passive: true });
window.addEventListener("resize", API_PLAYER_SCROLL);

API_PLAYER_SCROLL();

